### ISSUE TITLE
Cleanup unused files

### ISSUE THREAD

**Issue by MakisH** [precice/community-training#13]
@Ccaccia73 I have the impression that the `99_old` directory is not needed anymore. Correct?

Anything else we should remove? Is everything in the `10_utils` still being used?

**Comment by Ccaccia73** [comment]
I removed all `99_old` and `20_test` because they are not used. I also removed the conversion files in `10_utils` because we put all of them where needed. I only left a Python file that computes some properties of the naca2312 profile. We give some of the results from it in the solidSimulation. We could remove it or leave it just in case.

**Comment by MakisH** [comment]
I don't see any immediate unused files or commented-out parts anymore. Nice!
